"""The PDF is a document, not a picture of one.

⛔ WHAT THIS EXISTS TO PREVENT. The tempting way to build this was `html2canvas` over the
rendered brief. It would have produced a plausible-looking file and failed at everything that
matters: the glass theme is white text on near-black over a video, so it rasterises to an
unreadable page or, once a printer drops backgrounds, to nothing; and an image has no text at
all — a medicine name cannot be copied, searched, read by a screen reader, or ingested by a
hospital system.

So these tests pull the text back OUT of the generated bytes and assert the clinical content
is there as characters. A screenshot-based renderer fails every one of them.

The footer assertion is the other half. A pre-consultation history that a reader mistakes for
an assessment has been misled by the format rather than the content, so the disclaimer is on
EVERY page — asserted per page, not "somewhere in the document".
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

import pytest

from app.db.durable import ClinicalFactRecord, Encounter, Patient, SourceEvidence
from app.modules.report import pdf
from app.modules.report.brief import assemble
from app.modules.report.loader import Rows
from app.modules.report.patient_view import to_patient_view

pypdf = pytest.importorskip("pypdf", reason="pypdf is needed to read the PDF back")


def _rows(*, synthetic: bool = False) -> Rows:
    patient = Patient(
        id=1, patient_ref="pat_pdf", display_name="Test Patient",
        year_of_birth=1970, gender="female", is_synthetic=synthetic,
    )
    encounter = Encounter(
        id=1, encounter_ref="enc_pdf", patient_id=1,
        occurred_at=datetime(2026, 1, 18, tzinfo=UTC), kind="intake",
        headline="Stomach problem", confirmed_by="dr.mehta@aiia",
        confirmed_at=datetime(2026, 1, 18, tzinfo=UTC), priority="routine",
    )
    fact = ClinicalFactRecord(
        id=1, encounter_id=1, fact_ref="fact_pdf1", path="chief_complaint.text",
        value_json={"v": "stomach"}, display_value="Burning stomach pain",
        tier="confirmed", state="confirmed", confidence=1.0,
        recorded_at=encounter.occurred_at, valid_from=encounter.occurred_at,
    )
    evidence = SourceEvidence(
        id=1, fact_id=1, source_type="utterance",
        verbatim="my stomach burns", language="en", modality="touch",
    )
    return Rows(
        patient=patient, encounters=[encounter], current=encounter, previous=None,
        facts=[fact], prior_facts=[], evidence={1: [evidence]},
    )


def _pages(data: bytes) -> list[str]:
    reader = pypdf.PdfReader(__import__("io").BytesIO(data))
    return [p.extract_text() or "" for p in reader.pages]


@pytest.fixture
def clinician_pdf() -> bytes:
    return pdf.render(assemble(_rows()), audience="clinician", demo=False)


def test_the_text_is_real_text_not_an_image(clinician_pdf: bytes) -> None:
    """The single assertion a screenshot-based renderer cannot pass."""
    pages = _pages(clinician_pdf)
    body = "\n".join(pages)
    assert len(body) > 300, "almost no extractable text — this is an image, not a document"
    assert "Burning stomach pain" in body, (
        "the recorded value is not present as characters; it cannot be copied or searched"
    )


def test_the_not_a_diagnosis_notice_is_on_every_page(clinician_pdf: bytes) -> None:
    """Format misleads faster than content. This must not be a title-page-only disclaimer."""
    for i, page in enumerate(_pages(clinician_pdf), 1):
        assert "NOT a diagnosis" in page, f"page {i} carries no disclaimer"


def test_every_page_is_numbered_and_knows_the_total(clinician_pdf: bytes) -> None:
    """A clinical printout nobody can tell is complete is a hazard in a paper file."""
    pages = _pages(clinician_pdf)
    for i, page in enumerate(pages, 1):
        match = re.search(r"Page (\d+) of (\d+)", page)
        assert match, f"page {i} has no page number"
        assert match.group(1) == str(i)
        assert match.group(2) == str(len(pages)), (
            "the total is wrong — the second layout pass did not run"
        )


def test_the_wordmark_and_encounter_identity_are_present(clinician_pdf: bytes) -> None:
    """What makes a printout filable: whose it is, and which visit."""
    body = "\n".join(_pages(clinician_pdf))
    assert "MediKiosk" in body
    assert "enc_pdf" in body, "no encounter reference — the page cannot be filed"
    assert "2026-01-18" in body, "no encounter date"


def test_a_synthetic_record_is_badged_on_every_page() -> None:
    """A demo PDF leaving the room without its marking is the whole risk of guest mode."""
    data = pdf.render(assemble(_rows(synthetic=True)), audience="clinician", demo=True)
    for i, page in enumerate(_pages(data), 1):
        assert "SYNTHETIC DATA" in page, f"page {i} of a demo report is unbadged"


def test_a_clinical_record_is_not_badged() -> None:
    """The badge must mean something, so it may not appear on a non-demo report."""
    body = "\n".join(_pages(pdf.render(assemble(_rows()), audience="clinician", demo=False)))
    assert "SYNTHETIC DATA" not in body


def test_the_patient_pdf_leaks_no_internal_identifier() -> None:
    """Same payload, patient grouping — and none of our bookkeeping."""
    payload = to_patient_view(assemble(_rows()))
    body = "\n".join(_pages(pdf.render(payload, audience="patient", demo=False)))
    for leak in ("fact_pdf", "enc_pdf", "pat_pdf", "chief_complaint.", "confirmed"):
        assert leak not in body, f"the patient's copy exposes {leak!r}"
    assert "Burning stomach pain" in body, "the patient's own answer is missing"


def test_both_audiences_render_from_one_payload() -> None:
    """Two documents, one assembled brief — never two sources of truth about a record."""
    payload = assemble(_rows())
    clinician = pdf.render(payload, audience="clinician", demo=False)
    patient = pdf.render(to_patient_view(payload), audience="patient", demo=False)
    assert clinician[:4] == b"%PDF" and patient[:4] == b"%PDF"
    assert clinician != patient


def test_rendering_twice_does_not_reuse_flowables() -> None:
    """ReportLab MUTATES flowables during layout, so a story cannot be built twice.

    This is what the two-pass page numbering originally tripped over, and the failure was
    reported as a geometry error about a 15pt heading in a 665pt frame. Rendering the same
    payload twice in a row is the cheapest way to catch it coming back.
    """
    payload = assemble(_rows())
    first = pdf.render(payload, audience="clinician", demo=False)
    second = pdf.render(payload, audience="clinician", demo=False)
    assert len(first) > 1000 and len(second) > 1000
    assert _pages(first)[0][:200] == _pages(second)[0][:200]
