"""initial medikiosk schema

Revision ID: 9b8e1f47140d
Revises: 
Create Date: 2026-08-24 01:02:45.658679
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '9b8e1f47140d'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=64), nullable=False),
    sa.Column('purpose_of_use', sa.String(length=32), nullable=False),
    sa.Column('abha_ref', sa.String(length=128), nullable=True),
    sa.Column('consent_ref', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('request_summary', sa.JSON(), nullable=True),
    sa.Column('response_summary', sa.JSON(), nullable=True),
    sa.Column('versions_used', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_hash'), 'audit_event', ['hash'], unique=False)
    op.create_table('code_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('content_mode', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'version', name='uq_code_system_url_version')
    )
    op.create_index(op.f('ix_code_system_url'), 'code_system', ['url'], unique=False)
    op.create_table('consent_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_ref', sa.String(length=64), nullable=False),
    sa.Column('abha_ref', sa.String(length=128), nullable=True),
    sa.Column('session_ref', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('scopes_granted', sa.JSON(), nullable=True),
    sa.Column('scopes_refused', sa.JSON(), nullable=True),
    sa.Column('audio_explained', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_record_abha_ref'), 'consent_record', ['abha_ref'], unique=False)
    op.create_index(op.f('ix_consent_record_consent_ref'), 'consent_record', ['consent_ref'], unique=True)
    op.create_index(op.f('ix_consent_record_session_ref'), 'consent_record', ['session_ref'], unique=False)
    op.create_table('intake_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_ref', sa.String(length=64), nullable=False),
    sa.Column('abha_ref', sa.String(length=128), nullable=True),
    sa.Column('consent_ref', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('ayush_mode', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_session_abha_ref'), 'intake_session', ['abha_ref'], unique=False)
    op.create_index(op.f('ix_intake_session_expires_at'), 'intake_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_intake_session_session_ref'), 'intake_session', ['session_ref'], unique=True)
    op.create_index(op.f('ix_intake_session_status'), 'intake_session', ['status'], unique=False)
    op.create_table('submitted_bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(length=64), nullable=False),
    sa.Column('session_ref', sa.String(length=64), nullable=False),
    sa.Column('abha_ref', sa.String(length=128), nullable=True),
    sa.Column('consent_ref', sa.String(length=64), nullable=False),
    sa.Column('committed_by', sa.String(length=255), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fhir_version', sa.String(length=16), nullable=False),
    sa.Column('bundle_json', sa.JSON(), nullable=True),
    sa.Column('his_status', sa.String(length=32), nullable=False),
    sa.Column('his_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submitted_bundle_abha_ref'), 'submitted_bundle', ['abha_ref'], unique=False)
    op.create_index(op.f('ix_submitted_bundle_bundle_id'), 'submitted_bundle', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_submitted_bundle_session_ref'), 'submitted_bundle', ['session_ref'], unique=False)
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display', sa.Text(), nullable=False),
    sa.Column('display_normalized', sa.Text(), nullable=True),
    sa.Column('class_kind', sa.String(length=32), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('foundation_uri', sa.String(length=512), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['code_system_id'], ['code_system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_system_id', 'code', name='uq_concept_system_code')
    )
    op.create_index(op.f('ix_concept_code'), 'concept', ['code'], unique=False)
    op.create_index(op.f('ix_concept_display_normalized'), 'concept', ['display_normalized'], unique=False)
    op.create_index('ix_concept_normalized', 'concept', ['code_system_id', 'display_normalized'], unique=False)
    op.create_table('red_flag_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('proposed_by', sa.String(length=32), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('triggering_fact_ids', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intake_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_flag_proposal_rule_id'), 'red_flag_proposal', ['rule_id'], unique=False)
    op.create_index(op.f('ix_red_flag_proposal_session_id'), 'red_flag_proposal', ['session_id'], unique=False)
    op.create_table('session_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('ocr_backend', sa.String(length=32), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('pages_json', sa.JSON(), nullable=True),
    sa.Column('entities_json', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intake_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_document_document_id'), 'session_document', ['document_id'], unique=False)
    op.create_index(op.f('ix_session_document_session_id'), 'session_document', ['session_id'], unique=False)
    op.create_table('session_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_json', sa.JSON(), nullable=True),
    sa.Column('superseded_by', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intake_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_fact_fact_id'), 'session_fact', ['fact_id'], unique=False)
    op.create_index('ix_session_fact_path', 'session_fact', ['session_id', 'path'], unique=False)
    op.create_index(op.f('ix_session_fact_session_id'), 'session_fact', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_fact_session_id'), table_name='session_fact')
    op.drop_index('ix_session_fact_path', table_name='session_fact')
    op.drop_index(op.f('ix_session_fact_fact_id'), table_name='session_fact')
    op.drop_table('session_fact')
    op.drop_index(op.f('ix_session_document_session_id'), table_name='session_document')
    op.drop_index(op.f('ix_session_document_document_id'), table_name='session_document')
    op.drop_table('session_document')
    op.drop_index(op.f('ix_red_flag_proposal_session_id'), table_name='red_flag_proposal')
    op.drop_index(op.f('ix_red_flag_proposal_rule_id'), table_name='red_flag_proposal')
    op.drop_table('red_flag_proposal')
    op.drop_index('ix_concept_normalized', table_name='concept')
    op.drop_index(op.f('ix_concept_display_normalized'), table_name='concept')
    op.drop_index(op.f('ix_concept_code'), table_name='concept')
    op.drop_table('concept')
    op.drop_index(op.f('ix_submitted_bundle_session_ref'), table_name='submitted_bundle')
    op.drop_index(op.f('ix_submitted_bundle_bundle_id'), table_name='submitted_bundle')
    op.drop_index(op.f('ix_submitted_bundle_abha_ref'), table_name='submitted_bundle')
    op.drop_table('submitted_bundle')
    op.drop_index(op.f('ix_intake_session_status'), table_name='intake_session')
    op.drop_index(op.f('ix_intake_session_session_ref'), table_name='intake_session')
    op.drop_index(op.f('ix_intake_session_expires_at'), table_name='intake_session')
    op.drop_index(op.f('ix_intake_session_abha_ref'), table_name='intake_session')
    op.drop_table('intake_session')
    op.drop_index(op.f('ix_consent_record_session_ref'), table_name='consent_record')
    op.drop_index(op.f('ix_consent_record_consent_ref'), table_name='consent_record')
    op.drop_index(op.f('ix_consent_record_abha_ref'), table_name='consent_record')
    op.drop_table('consent_record')
    op.drop_index(op.f('ix_code_system_url'), table_name='code_system')
    op.drop_table('code_system')
    op.drop_index(op.f('ix_audit_event_hash'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
