"""The brief as a PDF, rendered server-side from the same deterministic payload.

⛔ NOT A SCREENSHOT OF THE DOM. `html2canvas` and friends would rasterise the glass theme —
white text on near-black, blurred, over a video — into something that is either a solid dark
page or, once a printer drops backgrounds, invisible. It also produces an IMAGE: no
selectable text, no copyable medicine name, nothing a screen reader or a hospital system can
read. A clinical document that cannot be searched or quoted is a picture of a document.

So this draws from `brief.assemble()` — the same dict the screen renders — through ReportLab,
with real embedded Inter and real text runs. `tests/test_pdf_export.py` extracts the text
back out of the generated bytes and asserts the medicine names are there as characters.

WHY REPORTLAB AND NOT WEASYPRINT. WeasyPrint would let the print stylesheet be actual CSS,
which is tempting. It also needs pango, cairo and harfbuzz as SYSTEM packages in the Docker
image — a real addition to a deployment that has just landed cleanly. ReportLab was already
a dependency, needs nothing from apt, and gives first-class control of the two things this
document must not get wrong: a footer on EVERY page, and page numbers that are correct
because they are stamped after pagination rather than guessed during it.

TWO AUDIENCES, ONE PAYLOAD. The clinician PDF and the patient PDF are rendered from the same
assembled brief — the patient one through `to_patient_view()`, exactly as the screen does. A
separately-built patient PDF would be a second source of truth about someone's own health.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.modules.report import print_theme as T
from app.modules.report.brief import REPORT_VERSION

FONT_DIR = Path(__file__).resolve().parents[3] / "data" / "fonts"

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm
FOOTER_H = 16 * mm

#: On every page, without exception. The single most important string in the document: this
#: is a history gathered before a consultation, and a reader who mistakes it for an
#: assessment has been misled by the format rather than by the content.
FOOTER_NOTICE = (
    "Pre-consultation clinical history. This is NOT a diagnosis, an assessment or a "
    "treatment recommendation."
)

_fonts_registered = False


def _register_fonts() -> None:
    """Embed Inter, and register it as a FAMILY.

    ⛔ THE FAMILY REGISTRATION IS NOT OPTIONAL, and its absence produced one of the more
    misleading errors in this project. Without `registerFontFamily`, ReportLab cannot resolve
    `<font name="Inter-Bold">` inside a paragraph whose style is `Inter`, and `<i>` has no
    face to map to. It raises deep inside the paragraph parser during trial layout — and the
    build then reports

        LayoutError: Flowable <Paragraph>Laboratory values(481 x 15.6) too large on page 1
                     in frame 'normal'(481 x 665)

    which is a geometry complaint about a 15pt heading in a 665pt frame. Two rewrites of the
    frame arithmetic later, the actual message was `Can't map determine family/bold/italic
    for inter`. Bisecting the story flowable by flowable is what surfaced it.
    """
    global _fonts_registered
    if _fonts_registered:
        return
    faces = {
        T.FONT: "Inter-Regular.ttf",
        T.FONT_SEMIBOLD: "Inter-SemiBold.ttf",
        T.FONT_BOLD: "Inter-Bold.ttf",
        T.FONT_ITALIC: "Inter-Italic.ttf",
    }
    try:
        for name, filename in faces.items():
            pdfmetrics.registerFont(TTFont(name, str(FONT_DIR / filename)))
        pdfmetrics.registerFontFamily(
            T.FONT,
            normal=T.FONT,
            bold=T.FONT_BOLD,
            italic=T.FONT_ITALIC,
            boldItalic=T.FONT_BOLD,
        )
        # The semibold face is used as a style fontName in its own right, so it needs a
        # family too or the same parser error returns for any markup inside a heading.
        pdfmetrics.registerFontFamily(
            T.FONT_SEMIBOLD,
            normal=T.FONT_SEMIBOLD,
            bold=T.FONT_BOLD,
            italic=T.FONT_ITALIC,
            boldItalic=T.FONT_BOLD,
        )
        pdfmetrics.registerFontFamily(
            T.FONT_BOLD, normal=T.FONT_BOLD, bold=T.FONT_BOLD,
            italic=T.FONT_ITALIC, boldItalic=T.FONT_BOLD,
        )
    except Exception:
        # A missing font must not stop a physician getting the document. Helvetica is a
        # base-14 face that needs no embedding; the text stays selectable and the layout
        # stays correct, and only the typeface changes.
        for name in (T.FONT, T.FONT_SEMIBOLD, T.FONT_BOLD, T.FONT_ITALIC):
            pdfmetrics.registerFontFamily(
                name, normal="Helvetica", bold="Helvetica-Bold",
                italic="Helvetica-Oblique", boldItalic="Helvetica-BoldOblique",
            )
    _fonts_registered = True


def _styles() -> dict[str, ParagraphStyle]:
    base = ParagraphStyle(
        "body",
        fontName=T.FONT,
        fontSize=T.SIZE_BODY,
        leading=T.LEADING_BODY,
        textColor=T.INK,
        alignment=TA_LEFT,
    )
    return {
        "body": base,
        "h1": ParagraphStyle("h1", parent=base, fontName=T.FONT_BOLD, fontSize=T.SIZE_H1,
                             leading=T.SIZE_H1 * 1.15, spaceAfter=2),
        "h2": ParagraphStyle("h2", parent=base, fontName=T.FONT_SEMIBOLD, fontSize=T.SIZE_H2,
                             leading=T.SIZE_H2 * 1.25, textColor=T.INK,
                             spaceBefore=9, spaceAfter=4),
        "h3": ParagraphStyle("h3", parent=base, fontName=T.FONT_SEMIBOLD, fontSize=T.SIZE_H3,
                             textColor=T.INK_MUTED, spaceBefore=6, spaceAfter=2),
        "meta": ParagraphStyle("meta", parent=base, fontSize=T.SIZE_SMALL,
                               textColor=T.INK_MUTED, leading=11),
        "small": ParagraphStyle("small", parent=base, fontSize=T.SIZE_SMALL, leading=11),
        "tiny": ParagraphStyle("tiny", parent=base, fontSize=T.SIZE_TINY,
                               textColor=T.INK_FAINT, leading=9.5),
        # An empty section states its reason, in italic-weight muted ink — the same
        # decision the screen makes. Never "None", which is an assertion nobody made.
        "empty": ParagraphStyle("empty", parent=base, fontSize=T.SIZE_SMALL,
                                textColor=T.INK_MUTED, leading=11),
    }


def _flag_suffix(point: dict[str, Any]) -> str:
    """The range flag, spelled as words. `in_range` is a column value, not English."""
    flag = point.get("rangeFlag")
    return f"  {flag.replace('_', ' ')}" if flag and flag != "unknown" else ""


def _esc(value: Any) -> str:
    """ReportLab paragraphs are mini-HTML, so raw text must be escaped."""
    return (
        str(value if value is not None else "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


class _Doc(SimpleDocTemplate):
    """Stamps the footer, the page number and the demo stripe on EVERY page.

    SimpleDocTemplate rather than a hand-built BaseDocTemplate + Frame. The first version
    computed the frame geometry by hand and ReportLab rejected a 15pt heading as "too large"
    in a 682pt frame — the arithmetic was subtly wrong in a way the error message did not
    describe. SimpleDocTemplate derives the frame from the margins, so `bottomMargin` alone
    reserves the footer band and there is no second place for it to disagree.

    `total_pages` is filled in by a second build pass: "Page 3 of 7" cannot be known while
    page 3 is being laid out, and a clinical document with wrong pagination is one nobody can
    tell is complete.
    """

    def __init__(self, buffer: io.BytesIO, *, title: str, demo: bool, audience: str) -> None:
        super().__init__(
            buffer,
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            # The demo band sits in the top margin, so make room for it only when it exists.
            topMargin=MARGIN + (6 * mm if demo else 0),
            bottomMargin=MARGIN + FOOTER_H,
            title=title,
            author="MediKiosk",
            subject="Pre-consultation clinical history — not a diagnosis",
        )
        self.demo = demo
        self.audience = audience
        self.total_pages = 0

    def build(self, flowables, **kw):  # noqa: ANN001, ANN003, A003
        return super().build(flowables, onFirstPage=self._chrome, onLaterPages=self._chrome)

    def _chrome(self, canvas, doc) -> None:  # noqa: ANN001
        canvas.saveState()

        if self.demo:
            # A solid band, not a watermark. A watermark behind text is the thing that gets
            # cropped, faded or ignored; a band at the top of every page is not.
            canvas.setFillColor(T.DEMO_TINT)
            canvas.rect(0, PAGE_H - 9 * mm, PAGE_W, 9 * mm, stroke=0, fill=1)
            canvas.setFillColor(T.DEMO)
            canvas.setFont(T.FONT_BOLD, T.SIZE_TINY)
            canvas.drawCentredString(
                PAGE_W / 2, PAGE_H - 6 * mm,
                "DEMO — SYNTHETIC DATA. NOT A REAL PATIENT.",
            )

        y = MARGIN + FOOTER_H - 5 * mm
        canvas.setStrokeColor(T.RULE)
        canvas.setLineWidth(0.6)
        canvas.line(MARGIN, y + 6 * mm, PAGE_W - MARGIN, y + 6 * mm)

        canvas.setFont(T.FONT, T.SIZE_TINY)
        canvas.setFillColor(T.INK_MUTED)
        canvas.drawString(MARGIN, y + 2.5 * mm, FOOTER_NOTICE)

        canvas.setFillColor(T.INK_FAINT)
        canvas.drawString(MARGIN, y - 1 * mm, f"MediKiosk · report version {REPORT_VERSION}")
        label = f"Page {canvas.getPageNumber()}"
        if self.total_pages:
            label += f" of {self.total_pages}"
        canvas.drawRightString(PAGE_W - MARGIN, y - 1 * mm, label)
        canvas.restoreState()


def _wordmark(canvas_text: str = "MediKiosk") -> Table:
    """The mark, drawn as type rather than an image so it stays crisp and selectable."""
    st = _styles()
    return Table(
        [[Paragraph(f'<font name="{T.FONT_BOLD}" size="13">{canvas_text}</font>', st["body"]),
          Paragraph(
              '<font size="7.5">Pre-consultation clinical history</font>', st["tiny"])]],
        colWidths=[40 * mm, None],
        style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("LINEBELOW", (0, 0), (-1, -1), 1.1, T.ACCENT),
        ]),
    )


def _kv_table(rows: list[tuple[str, str]], *, label_w: float = 45 * mm) -> Table:
    st = _styles()
    data = [
        [Paragraph(_esc(k), st["meta"]), Paragraph(_esc(v), st["body"])] for k, v in rows
    ]
    return Table(
        data,
        colWidths=[label_w, None],
        style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LINEBELOW", (0, 0), (-1, -2), 0.4, T.RULE),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ]),
    )


def _section(title: str, flowables: list, *, empty_reason: str | None = None) -> list:
    st = _styles()
    out: list = [Paragraph(_esc(title), st["h2"])]
    if empty_reason:
        out.append(Paragraph(f"<i>{_esc(empty_reason)}</i>", st["empty"]))
    else:
        out.extend(flowables)
    return out


# ────────────────────────────────────────────────────────── clinician


def _clinician_story(payload: dict[str, Any]) -> list:
    st = _styles()
    story: list = [_wordmark(), Spacer(1, 8)]

    header = payload["header"]
    enc = header.get("encounter") or {}
    story.append(Paragraph(_esc(header.get("displayName") or header["patientRef"]), st["h1"]))
    story.append(Paragraph(
        _esc(" · ".join(str(x) for x in [
            f"{header['ageYears']} years" if header.get("ageYears") is not None else None,
            header.get("gender"),
            f"{header.get('encounterCount', 0)} recorded visit(s)",
        ] if x)), st["meta"]))
    story.append(Spacer(1, 6))

    # Encounter identity, which is what makes a printout filable.
    story.append(_kv_table([
        ("Encounter date", enc.get("occurredOn") or "—"),
        ("Encounter reference", enc.get("encounterRef") or "—"),
        ("Patient reference", header["patientRef"]),
        ("Consent reference", enc.get("consentRef") or "not recorded"),
        ("Priority", (enc.get("priority") or "routine").replace("_", " ")),
    ]))
    story.append(Spacer(1, 4))

    # ── escalations ──
    flags = payload["redFlags"]
    story += _section("Escalations", [
        _kv_table([(f.get("level") or "urgent", f.get("rationale") or f["ruleId"])
                   for f in flags["items"]], label_w=25 * mm)
    ] if flags["items"] else [], empty_reason=flags.get("emptyReason"))

    # ── what changed ──
    wc = payload["whatChanged"]
    changed_flow: list = []
    if wc.get("comparedWith"):
        changed_flow.append(Paragraph(
            f"Compared with the visit of <b>{_esc(wc['comparedWith']['occurredOn'])}</b>"
            + (
                f" — {_esc(wc['comparedWith']['headline'])}"
                if wc["comparedWith"].get("headline")
                else ""
            ),
            st["meta"]))
        changed_flow.append(Spacer(1, 3))
        for label, key in (("New this visit", "new"),
                           ("Not recorded this visit", "resolved"),
                           ("Same as before", "persisting")):
            items = wc.get(key) or []
            changed_flow.append(Paragraph(f"{_esc(label)} ({len(items)})", st["h3"]))
            changed_flow.append(Paragraph(
                _esc("; ".join(i["value"] for i in items)) if items else "<i>none</i>",
                st["small"]))
    story += _section("What changed?", changed_flow, empty_reason=wc.get("emptyReason"))

    # ── snapshot ──
    snap = payload["snapshot"]
    snap_flow: list = []
    if snap["items"]:
        snap_flow.append(_kv_table(
            [(i["label"], i.get("displayValue") or i.get("value")) for i in snap["items"]]))
    if snap["allergies"]:
        snap_flow += [Paragraph("Allergies", st["h3"]),
                      _kv_table([(a["label"], a.get("displayValue") or a.get("value"))
                                 for a in snap["allergies"]])]
    if snap["reportedMedications"]:
        snap_flow.append(Paragraph("Medicines on the patient's papers", st["h3"]))
        snap_flow.append(_kv_table(
            [(m.get("name") or "—",
              " · ".join(str(x) for x in [m.get("dose"), m.get("frequency")] if x) or "—")
             for m in snap["reportedMedications"]]))
    story += _section("Current clinical snapshot", snap_flow,
                      empty_reason=snap.get("emptyReason"))

    # ── labs ──
    obs = payload["observations"]
    lab_flow: list = []
    for s in obs.get("series", []):
        pts = "   ".join(
            f"{pt['observedOn']}: {pt['value']}"
            f"{(' ' + pt['unit']) if pt.get('unit') else ''}"
            f"{_flag_suffix(pt)}"
            for pt in s["points"])
        lab_flow.append(Paragraph(f"<b>{_esc(s['display'])}</b>", st["small"]))
        lab_flow.append(Paragraph(_esc(pts), st["tiny"]))
        lab_flow.append(Spacer(1, 2))
    for s in obs.get("singles", []):
        p0 = (s.get("points") or [{}])[0]
        lab_flow.append(Paragraph(
            f"<b>{_esc(s['display'])}</b> {_esc(p0.get('value'))}"
            f"{(' ' + str(p0.get('unit'))) if p0.get('unit') else ''}", st["small"]))
        lab_flow.append(Paragraph(_esc(s.get("notChartableBecause") or ""), st["tiny"]))
    if lab_flow:
        lab_flow.append(Paragraph(_esc(obs.get("note") or ""), st["tiny"]))
    story += _section("Laboratory values", lab_flow, empty_reason=obs.get("emptyReason"))

    # ── medications ──
    meds = payload["medications"]
    med_flow: list = []
    if meds["items"]:
        data = [[Paragraph(f"<b>{h}</b>", st["tiny"]) for h in
                 ("Medicine", "Dose", "Frequency", "How we know", "When")]]
        for m in meds["items"]:
            data.append([Paragraph(_esc(v), st["tiny"]) for v in (
                m.get("name"), m.get("dose") or "—", m.get("frequency") or "—",
                (m.get("status") or "").replace("_", " "), m.get("observedOn") or "—")])
        med_flow.append(Table(data, colWidths=[45 * mm, 20 * mm, 25 * mm, 40 * mm, None],
            style=TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LINEBELOW", (0, 0), (-1, 0), 0.7, T.RULE_STRONG),
                ("LINEBELOW", (0, 1), (-1, -2), 0.3, T.RULE),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ])))
        med_flow.append(Paragraph(_esc(meds.get("note") or ""), st["tiny"]))
    story += _section("Medication history", med_flow, empty_reason=meds.get("emptyReason"))

    # ── timeline ──
    tl = payload["timeline"]
    story += _section("Visit timeline", [
        _kv_table([(t["occurredOn"], f"{t.get('headline') or 'Intake'} — {t['confirmedBy']}")
                   for t in tl["items"]], label_w=28 * mm)
    ] if tl["items"] else [], empty_reason=tl.get("emptyReason"))

    # ── similar ──
    sim = payload["similarEncounters"]
    story += _section("Similar earlier visits", [
        _kv_table(
            [
                (e["occurredOn"], f"{e['why']} " + "; ".join(
                    f["value"] for f in e["sharedFeatures"]))
                for e in sim["items"]
            ],
            label_w=28 * mm,
        )
    ] if sim["items"] else [], empty_reason=sim.get("emptyReason"))

    # ── contradictions ──
    con = payload["contradictions"]
    story += _section("Contradictions", [
        _kv_table([(c["label"], "Both recorded sources are shown on screen; neither has been "
                                "chosen.") for c in con["items"]], label_w=55 * mm)
    ] if con["items"] else [], empty_reason=con.get("emptyReason"))

    # ── unresolved ──
    un = payload["unresolved"]
    un_flow: list = []
    for label, key, field in (("Declined or unknown", "declinedOrUnknown", "state"),
                              ("Answers the patient changed", "superseded", "wasValue"),
                              ("Ruled out as not applicable", "invalidated", "reason")):
        items = un.get(key) or []
        if items:
            un_flow.append(Paragraph(label, st["h3"]))
            un_flow.append(_kv_table([(i["path"], _esc(i.get(field))) for i in items]))
    if un_flow:
        un_flow.append(Paragraph(_esc(un.get("note") or ""), st["tiny"]))
    story += _section("Unresolved and changed", un_flow, empty_reason=un.get("emptyReason"))

    # ── completeness ──
    comp = payload["completeness"]
    story += _section("Intake completeness", [
        _kv_table([
            ("Collected", ", ".join(comp["collected"]) or "none"),
            ("Declined", ", ".join(comp["declined"]) or "none"),
            ("Not asked or unanswered", ", ".join(comp["missing"]) or "none"),
        ], label_w=45 * mm),
        Paragraph(_esc(comp.get("note") or ""), st["tiny"]),
    ])

    # ── source references ──
    #: The printed equivalent of click-to-source. A PDF cannot open a drawer, so each line's
    #: fact reference is listed — the identifier a physician can quote back to look it up.
    refs: list[tuple[str, str]] = []
    for item in snap["items"] + snap["allergies"]:
        refs.append((item["label"], f"{item['factRef']} · {', '.join(item['evidenceKinds'])}"))
    for group in snap["reportedMedications"]:
        for line in group["lines"]:
            refs.append((f"{group.get('name')} {line['label']}",
                         f"{line['factRef']} · {', '.join(line['evidenceKinds'])}"))
    story += _section("Source references", [
        Paragraph("Every line above is recorded with the source it came from. These are the "
                  "references to quote when looking one up in the system.", st["tiny"]),
        Spacer(1, 3),
        _kv_table(refs, label_w=55 * mm),
    ] if refs else [], empty_reason=None if refs else "No source-linked lines on this record.")

    # ── documents ──
    docs = {i.get("documentRef") for i in payload["medications"]["items"] if i.get("documentRef")}
    story += _section(
        "Document references",
        [_kv_table([(d, "Filed with this record") for d in sorted(docs)], label_w=55 * mm)]
        if docs
        else [],
        empty_reason=None if docs else "No documents are filed against this record.",
    )

    # ── confirmation ──
    conf = payload["confirmation"]
    story += _section("Verification and physician confirmation", [
        _kv_table([
            ("Confirmed", "Yes" if conf["confirmed"] else "Not yet confirmed"),
            ("Confirmed by", conf.get("confirmedBy") or "—"),
            ("Confirmed at", (conf.get("confirmedAt") or "—")[:19].replace("T", " ")),
        ], label_w=45 * mm),
        Paragraph(_esc(conf.get("note") or ""), st["tiny"]),
    ])

    story.append(Spacer(1, 8))
    story.append(Paragraph(_esc(payload.get("notice") or ""), st["tiny"]))
    return story


# ────────────────────────────────────────────────────────── patient


def _patient_story(payload: dict[str, Any]) -> list:
    st = _styles()
    story: list = [_wordmark(), Spacer(1, 8)]
    story.append(Paragraph("Your visit", st["h1"]))
    if payload.get("forWhom"):
        story.append(Paragraph(_esc(payload["forWhom"]), st["meta"]))
    story.append(Spacer(1, 6))

    for group in payload.get("groups", []):
        items = group.get("items") or []
        story += _section(
            group["title"],
            [_kv_table([(i["label"], i.get("value")) for i in items], label_w=55 * mm)]
            if items else [],
            empty_reason=group.get("emptyReason"),
        )

    story.append(Spacer(1, 8))
    story.append(Paragraph(_esc(payload.get("notice") or ""), st["tiny"]))
    return story


# ────────────────────────────────────────────────────────── entry point


def render(payload: dict[str, Any], *, audience: str = "clinician", demo: bool = False) -> bytes:
    """The brief as PDF bytes. Same payload as the screen; text, never an image."""
    _register_fonts()

    name = payload.get("header", {}).get("displayName") or payload.get("forWhom") or "Patient"
    kind = "clinical history" if audience == "clinician" else "your visit"
    title = f"MediKiosk — {kind} — {name}"

    def story() -> list:
        """A FRESH story for every build pass.

        ⛔ REPORTLAB MUTATES FLOWABLES DURING LAYOUT. A Paragraph caches its wrapped lines,
        and a Table caches its computed row heights; feeding the same objects to a second
        `build()` fails — and it fails as

            LayoutError: Flowable <Paragraph>Laboratory values(481 x 15.6) too large on
                         page 1 in frame 'normal'(481 x 665)

        a geometry complaint about a 15pt heading in a 665pt frame. It cost two rewrites of
        the frame arithmetic and a font-family fix before a bisect showed that a no-op page
        callback worked and a drawing one did not — which was itself a red herring, because
        the *first* attempt in that loop had already consumed the flowables. Building the
        story twice is the whole fix.
        """
        return (
            _clinician_story(payload) if audience == "clinician" else _patient_story(payload)
        )

    # TWO PASSES. The first lays out to learn the page count; the second stamps "of N" into
    # the footer. Without it every page says "Page 1 of 1", and a printed clinical document
    # with wrong pagination is one nobody can tell is complete.
    buf = io.BytesIO()
    first = _Doc(buf, title=title, demo=demo, audience=audience)
    first.build(story())
    total = first.page

    buf = io.BytesIO()
    final = _Doc(buf, title=title, demo=demo, audience=audience)
    final.total_pages = total
    final.build(story())
    return buf.getvalue()


def filename_for(payload: dict[str, Any], *, audience: str, demo: bool) -> str:
    enc = (payload.get("header", {}).get("encounter") or {}).get("encounterRef")
    stamp = enc or datetime.now(UTC).strftime("%Y%m%d")
    prefix = "medikiosk-demo" if demo else "medikiosk"
    return f"{prefix}-{audience}-{stamp}.pdf"
